set(_CATKIN_CURRENT_PACKAGE "state_machine")
set(state_machine_MAINTAINER "sb161 <sb161@todo.todo>")
set(state_machine_DEPRECATED "")
set(state_machine_VERSION "0.0.0")
set(state_machine_BUILD_DEPENDS "roscpp" "std_msgs")
set(state_machine_RUN_DEPENDS "roscpp" "std_msgs")
set(state_machine_BUILDTOOL_DEPENDS "catkin")